spring.application.name=pms-backend

#spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.SQLServerDialect
spring.datasource.url=jdbc:sqlserver://localhost;trustServerCertificate=true;databaseName=pms_scco
spring.datasource.username=sql_user
spring.datasource.password=Siinqee@1234
spring.datasource.driverClassName=com.microsoft.sqlserver.jdbc.SQLServerDriver

spring.jpa.hibernate.ddl-auto=update

# JWT
app.jwt.secret=8d3fKx9LpQz7mT2vR4sY6nU1bC5xZ8pQ9lLmN7vT2kR4aW6e
app.jwt.expiration=86400000

# Super Admin
super.admin.first-name=Super
super.admin.middle-name=Admin
super.admin.last-name=Admin
super.admin.username=scco_super_admin
super.admin.password=GH**/&
super.admin.user-email=superadmin@scco.com

#spring.jpa.open-in-view=false

# Max size per individual file (e.g., a video)
spring.servlet.multipart.max-file-size=100MB
spring.servlet.multipart.max-request-size=150MB